# Generated by Django 4.1.4 on 2022-12-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=128)),
                ('reg_date', models.DateField()),
            ],
        ),
    ]
