# Generated by Django 4.1.4 on 2022-12-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_user_email_alter_user_name_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
