# Generated by Django 4.1.4 on 2022-12-23 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='reg_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reg_date',
        ),
    ]
